### ISSUE TITLE
The Plugin is Incompatible w/ EssX Discord

### ISSUE THREAD

**Issue by CallMeCanadian** [e-im/FreedomChat#25] opened 2023-03-17 15:52 UTC
Hello, I have been using your plugin for a few months now, and it has been working like a charm.

The problem is that it is not compatible with [EssentialsX Discord](https://essentialsx.net/downloads).
EssentialsX Discord works totally fine **aside from one thing**: EssX DC doesn't pick up chat messages from Minecraft, therefore is unable to send them to the Discord server.

It would be amazing if you could update the plugin to be compatible with EssX Discord, and it would likely be the only no-chat-reporting plugin that works with it!

Thanks!
- Canadian

**Comment by e-im** [comment] 2023-03-17 20:33
I haven't been able to replicate this issue. I tested this by setting up a new server with just `Essentials, EssentialsDiscord, FreedomChat` installed. I did not configure anything bar setting a bot token, guild, and primary channel for essx discord.

![msedge_c3YEDgqkr5](https://user-images.githubusercontent.com/76139600/226033339-cd045cf6-d954-4dda-9287-ce532a90d4d5.png)

Please let me know if anything else needs to be done to replicate this—this shouldn't be happening.

**Comment by CallMeCanadian** [comment] 2023-03-18 00:13
Hmm.. thanks. Well, funny enough, I've completely removed all Essentials plugins from my server for another reason.
I'm moving to DiscordSRV. Hopefully that works for me.. if it doesn't, I'll look into other possible reasons.

Thanks very much for the quick and thorough response! :)

**Comment by e-im** [comment] 2023-03-21 23:09
Closing this for the moment as cannot reproduce. Feel free to comment if you are still having the issue with discordsrv or have any more details.

**Closed** 2023-03-21 23:08 UTC
